-- Rampaging Chariots Supabase schema
-- Run this in the Supabase SQL editor for the project.

create table if not exists public.school_progress (
  id bigint generated by default as identity primary key,
  school text not null,
  password text not null,
  progress integer[] not null default '{}',
  comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_progress_school_unique unique (school),
  constraint school_progress_comments_array check (jsonb_typeof(comments) = 'array')
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_school_progress_updated_at on public.school_progress;
create trigger set_school_progress_updated_at
before update on public.school_progress
for each row
execute function public.set_updated_at();

alter table public.school_progress enable row level security;

drop policy if exists "No direct anon reads" on public.school_progress;
drop policy if exists "No direct anon writes" on public.school_progress;

revoke all on table public.school_progress from anon;
revoke all on table public.school_progress from authenticated;
revoke all on table public.school_progress from public;

create or replace function public.school_password_matches(p_school text, p_password text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.school_progress sp
    where lower(sp.school) = lower(trim(p_school))
      and sp.password = p_password
  );
$$;

create or replace function public.admin_password_matches(p_password text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.school_password_matches('Admin', p_password);
$$;

create or replace function public.get_school_names()
returns text[]
language sql
security definer
set search_path = public
as $$
  select coalesce(array_agg(sp.school order by sp.school), '{}'::text[])
  from public.school_progress sp;
$$;

create or replace function public.verify_school_password(p_name text, p_password text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object('success', public.school_password_matches(p_name, p_password));
$$;

create or replace function public.get_school_progress(p_name text, p_password text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (
      select jsonb_build_object('school', sp.school, 'progress', sp.progress)
      from public.school_progress sp
      where lower(sp.school) = lower(trim(p_name))
        and sp.password = p_password
      limit 1
    ),
    jsonb_build_object('error', 'School not found or incorrect password')
  );
$$;

create or replace function public.list_school_progress(
  p_name text default null,
  p_password text default null,
  p_admin_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not (
    public.admin_password_matches(coalesce(p_admin_key, ''))
    or public.school_password_matches(coalesce(p_name, ''), coalesce(p_password, ''))
  ) then
    raise exception 'Not authorised' using errcode = '28000';
  end if;

  return coalesce(
    (
      select jsonb_agg(jsonb_build_object('school', sp.school, 'progress', sp.progress) order by sp.school)
      from public.school_progress sp
    ),
    '[]'::jsonb
  );
end;
$$;

create or replace function public.create_school(p_admin_key text, p_name text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_school public.school_progress;
begin
  if not public.admin_password_matches(p_admin_key) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  if nullif(trim(p_name), '') is null or nullif(p_password, '') is null then
    raise exception 'School name and password are required' using errcode = '22023';
  end if;

  insert into public.school_progress (school, password, progress, comments)
  values (trim(p_name), p_password, '{}'::integer[], '[]'::jsonb)
  returning * into created_school;

  return jsonb_build_object(
    'school', created_school.school,
    'progress', created_school.progress,
    'comments', created_school.comments
  );
exception
  when unique_violation then
    raise exception 'School already exists' using errcode = '23505';
end;
$$;

create or replace function public.delete_school(p_admin_key text, p_name text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_school text;
begin
  if not public.admin_password_matches(p_admin_key) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  delete from public.school_progress sp
  where lower(sp.school) = lower(trim(p_name))
    and sp.password = p_password
    and sp.school <> 'Admin'
  returning sp.school into deleted_school;

  if deleted_school is null then
    raise exception 'School not found or incorrect password' using errcode = '02000';
  end if;

  return jsonb_build_object(
    'success', true,
    'message', format('School "%s" deleted successfully', deleted_school)
  );
end;
$$;

create or replace function public.update_school_progress(p_name text, p_password text, p_progress integer[])
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_school public.school_progress;
begin
  update public.school_progress sp
  set progress = coalesce(p_progress, '{}'::integer[])
  where lower(sp.school) = lower(trim(p_name))
    and sp.password = p_password
  returning * into updated_school;

  if updated_school.id is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  return jsonb_build_object('school', updated_school.school, 'progress', updated_school.progress);
end;
$$;

create or replace function public.reset_all_progress(p_admin_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.admin_password_matches(p_admin_key) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  update public.school_progress set progress = '{}'::integer[];
  return jsonb_build_object('success', true, 'message', 'All school progress has been reset');
end;
$$;

create or replace function public.get_comments(p_school_name text, p_school_key text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (
      select jsonb_build_object('comments', sp.comments)
      from public.school_progress sp
      where lower(sp.school) = lower(trim(p_school_name))
        and sp.password = p_school_key
      limit 1
    ),
    jsonb_build_object('error', 'School not found or incorrect password')
  );
$$;

create or replace function public.add_comment(
  p_school_name text,
  p_school_key text,
  p_text text,
  p_admin_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_row public.school_progress;
  current_comments jsonb;
  new_comment jsonb;
  new_index integer;
  sender text;
begin
  if nullif(trim(p_text), '') is null then
    raise exception 'Comment text is required' using errcode = '22023';
  end if;

  if p_admin_key is not null and not public.admin_password_matches(p_admin_key) then
    raise exception 'Incorrect admin key' using errcode = '28000';
  end if;

  select *
  into school_row
  from public.school_progress sp
  where lower(sp.school) = lower(trim(p_school_name))
    and sp.password = p_school_key
  for update;

  if school_row.id is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  current_comments := coalesce(school_row.comments, '[]'::jsonb);
  new_index := jsonb_array_length(current_comments);
  sender := case when p_admin_key is null then 'school' else 'leonardo' end;
  new_comment := jsonb_build_object('index', new_index, 'sender', sender, 'text', p_text, 'viewed', false);

  update public.school_progress
  set comments = current_comments || jsonb_build_array(new_comment)
  where id = school_row.id;

  return jsonb_build_object('success', true, 'comment', new_comment);
end;
$$;

create or replace function public.delete_comment(
  p_school_name text,
  p_school_key text,
  p_comment_index integer,
  p_admin_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_row public.school_progress;
  updated_comments jsonb;
begin
  if not public.admin_password_matches(p_admin_key) then
    raise exception 'Incorrect admin key' using errcode = '28000';
  end if;

  select *
  into school_row
  from public.school_progress sp
  where lower(sp.school) = lower(trim(p_school_name))
    and sp.password = p_school_key
  for update;

  if school_row.id is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  if p_comment_index < 0 or p_comment_index >= jsonb_array_length(school_row.comments) then
    raise exception 'Invalid comment index' using errcode = '22023';
  end if;

  select coalesce(
    jsonb_agg((comment - 'index') || jsonb_build_object('index', new_index) order by new_index),
    '[]'::jsonb
  )
  into updated_comments
  from (
    select
      comment,
      row_number() over (order by ordinality) - 1 as new_index
    from jsonb_array_elements(school_row.comments) with ordinality as items(comment, ordinality)
    where (comment->>'index')::integer <> p_comment_index
  ) reindexed;

  update public.school_progress
  set comments = updated_comments
  where id = school_row.id;

  return jsonb_build_object('success', true, 'comments', updated_comments);
end;
$$;

create or replace function public.mark_comment_viewed(
  p_school_name text,
  p_school_key text,
  p_msg_index integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_row public.school_progress;
  updated_comments jsonb;
  viewed_comment jsonb;
begin
  select *
  into school_row
  from public.school_progress sp
  where lower(sp.school) = lower(trim(p_school_name))
    and sp.password = p_school_key
  for update;

  if school_row.id is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  if p_msg_index < 0 or p_msg_index >= jsonb_array_length(school_row.comments) then
    raise exception 'Invalid message index' using errcode = '22023';
  end if;

  select jsonb_agg(
    case
      when (comment->>'index')::integer = p_msg_index then jsonb_set(comment, '{viewed}', 'true'::jsonb)
      else comment
    end
    order by ordinality
  )
  into updated_comments
  from jsonb_array_elements(school_row.comments) with ordinality as items(comment, ordinality);

  select comment
  into viewed_comment
  from jsonb_array_elements(updated_comments) comment
  where (comment->>'index')::integer = p_msg_index
  limit 1;

  update public.school_progress
  set comments = updated_comments
  where id = school_row.id;

  return jsonb_build_object('success', true, 'comment', viewed_comment);
end;
$$;

create or replace function public.get_unviewed_comments(p_admin_key text, p_sent_by text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.admin_password_matches(p_admin_key) then
    raise exception 'Incorrect admin key' using errcode = '28000';
  end if;

  select coalesce(jsonb_object_agg(school, unviewed_count), '{}'::jsonb)
  into result
  from (
    select sp.school, count(*)::integer as unviewed_count
    from public.school_progress sp
    cross join lateral jsonb_array_elements(sp.comments) comment
    where sp.school <> 'Admin'
      and (comment->>'viewed')::boolean = false
      and (
        p_sent_by is null
        or p_sent_by not in ('leonardo', 'school')
        or comment->>'sender' = p_sent_by
      )
    group by sp.school
  ) counts;

  return result;
end;
$$;

grant execute on function public.get_school_names() to anon, authenticated;
grant execute on function public.verify_school_password(text, text) to anon, authenticated;
grant execute on function public.get_school_progress(text, text) to anon, authenticated;
grant execute on function public.list_school_progress(text, text, text) to anon, authenticated;
grant execute on function public.create_school(text, text, text) to anon, authenticated;
grant execute on function public.delete_school(text, text, text) to anon, authenticated;
grant execute on function public.update_school_progress(text, text, integer[]) to anon, authenticated;
grant execute on function public.reset_all_progress(text) to anon, authenticated;
grant execute on function public.get_comments(text, text) to anon, authenticated;
grant execute on function public.add_comment(text, text, text, text) to anon, authenticated;
grant execute on function public.delete_comment(text, text, integer, text) to anon, authenticated;
grant execute on function public.mark_comment_viewed(text, text, integer) to anon, authenticated;
grant execute on function public.get_unviewed_comments(text, text) to anon, authenticated;

insert into public.school_progress (school, password, progress, comments)
values
  ('Admin', 'lu13pg', '{}'::integer[], '[]'::jsonb),
  ('Cottesloe', 'cottesloe37355', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Queensbury', 'queensbury67890', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Aylesbury High', 'aylesburyhigh54321', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Parmiters', 'parmiters98765', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Stopsley', 'stopsley11223', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Silverstone UTC', 'silverstoneutc44556', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Roundwood', 'roundwood77889', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Watford Boys', 'watfordboys99001', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Watford Girls', 'watfordgirls22334', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Chalk Hills', 'chalkhills55667', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('St Clement Danes', 'stclementdanes88990', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Lealands', 'lealands33445', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Chiltern Academy', 'chilternacademy66778', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Shenley Brook End', 'shenleybrookend91402', '{}'::integer[], '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb)
on conflict (school) do nothing;
