-- Rampaging Chariots Supabase schema
-- Run this in the Supabase SQL editor for the project.

do $$
begin
  if to_regclass('public.school_progress') is not null
    and to_regclass('public."Luton_schools"') is null then
    alter table public.school_progress rename to "Luton_schools";
  end if;
end;
$$;

create table if not exists public."Luton_schools" (
  id bigint generated by default as identity primary key,
  school text not null,
  password text not null,
  progress jsonb not null default '[]'::jsonb,
  comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint luton_schools_school_unique unique (school),
  constraint luton_schools_progress_array check (jsonb_typeof(progress) = 'array'),
  constraint luton_schools_comments_array check (jsonb_typeof(comments) = 'array')
);

create table if not exists public."Edinburgh_schools" (
  id bigint generated by default as identity primary key,
  school text not null,
  password text not null,
  progress jsonb not null default '[]'::jsonb,
  comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint edinburgh_schools_school_unique unique (school),
  constraint edinburgh_schools_progress_array check (jsonb_typeof(progress) = 'array'),
  constraint edinburgh_schools_comments_array check (jsonb_typeof(comments) = 'array')
);

create table if not exists public."Basildon_schools" (
  id bigint generated by default as identity primary key,
  school text not null,
  password text not null,
  progress jsonb not null default '[]'::jsonb,
  comments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint basildon_schools_school_unique unique (school),
  constraint basildon_schools_progress_array check (jsonb_typeof(progress) = 'array'),
  constraint basildon_schools_comments_array check (jsonb_typeof(comments) = 'array')
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_school_progress_updated_at on public."Luton_schools";
drop trigger if exists set_luton_schools_updated_at on public."Luton_schools";
create trigger set_luton_schools_updated_at
before update on public."Luton_schools"
for each row
execute function public.set_updated_at();

drop trigger if exists set_edinburgh_schools_updated_at on public."Edinburgh_schools";
create trigger set_edinburgh_schools_updated_at
before update on public."Edinburgh_schools"
for each row
execute function public.set_updated_at();

drop trigger if exists set_basildon_schools_updated_at on public."Basildon_schools";
create trigger set_basildon_schools_updated_at
before update on public."Basildon_schools"
for each row
execute function public.set_updated_at();

alter table public."Luton_schools" enable row level security;
alter table public."Edinburgh_schools" enable row level security;
alter table public."Basildon_schools" enable row level security;

drop policy if exists "No direct anon reads" on public."Luton_schools";
drop policy if exists "No direct anon writes" on public."Luton_schools";
drop policy if exists "No direct anon reads" on public."Edinburgh_schools";
drop policy if exists "No direct anon writes" on public."Edinburgh_schools";
drop policy if exists "No direct anon reads" on public."Basildon_schools";
drop policy if exists "No direct anon writes" on public."Basildon_schools";

revoke all on table public."Luton_schools" from anon;
revoke all on table public."Luton_schools" from authenticated;
revoke all on table public."Luton_schools" from public;
revoke all on table public."Edinburgh_schools" from anon;
revoke all on table public."Edinburgh_schools" from authenticated;
revoke all on table public."Edinburgh_schools" from public;
revoke all on table public."Basildon_schools" from anon;
revoke all on table public."Basildon_schools" from authenticated;
revoke all on table public."Basildon_schools" from public;

-- The admin progress page uploads directly to this public Storage bucket with the
-- publishable anon key, then stores the returned public URL via update_roadmap_image.
insert into storage.buckets (id, name, public)
values ('Roadmap-Images', 'Roadmap-Images', true)
on conflict (id) do update
set public = true;

drop policy if exists "Public roadmap image reads" on storage.objects;
drop policy if exists "Anon roadmap image uploads" on storage.objects;

create policy "Public roadmap image reads"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'Roadmap-Images');

create policy "Anon roadmap image uploads"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'Roadmap-Images');

drop function if exists public.school_password_matches(text, text);
drop function if exists public.admin_password_matches(text);

create or replace function public.site_schools_table(p_site text default 'Luton')
returns text
language sql
stable
as $$
  select case coalesce(nullif(trim(p_site), ''), 'Luton')
    when 'Luton' then 'Luton_schools'
    when 'Edinburgh' then 'Edinburgh_schools'
    when 'Basildon' then 'Basildon_schools'
    else 'Luton_schools'
  end;
$$;

create or replace function public.school_password_matches(
  p_school text,
  p_password text,
  p_site text default 'Luton'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  matched boolean;
  table_name text := public.site_schools_table(p_site);
begin
  execute format(
    'select exists (
      select 1
      from public.%I sp
      where lower(sp.school) = lower(trim($1))
        and sp.password = $2
    )',
    table_name
  )
  into matched
  using p_school, p_password;

  return matched;
end;
$$;

create or replace function public.admin_password_matches(
  p_password text,
  p_site text default 'Luton'
)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.school_password_matches('Admin', p_password, p_site);
$$;

create or replace function public.default_progress_steps()
returns jsonb
language sql
immutable
as $$
  select jsonb_build_array(
    jsonb_build_object('index', 0, 'title', 'Formed a team', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/team.jpeg'),
    jsonb_build_object('index', 1, 'title', 'Checked components & identified any missing parts', 'checked', false, 'page-text', 'Pages 63-65', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/parts.jpeg'),
    jsonb_build_object('index', 2, 'title', 'Received the kit', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/kit.jpeg'),
    jsonb_build_object('index', 3, 'title', 'Cut & drilled & counter-sunk holes in the MDF wood', 'checked', false, 'page-text', 'Pages 19-22', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/cutmdf.jpeg'),
    jsonb_build_object('index', 4, 'title', 'Cut & drilled & counter-sunk holes in aluminium brackets', 'checked', false, 'page-text', 'Pages 23-24', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/alum.jpeg'),
    jsonb_build_object('index', 5, 'title', 'Fully assembled the chassis', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/chassis.jpeg'),
    jsonb_build_object('index', 6, 'title', 'Replaced both drill chucks with wheels', 'checked', false, 'page-text', 'Pages 25', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/chuck.jpeg'),
    jsonb_build_object('index', 7, 'title', 'Dismantled both drills', 'checked', false, 'page-text', 'Pages 26-27', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/dsmtl.jpeg'),
    jsonb_build_object('index', 8, 'title', 'Cut drill cases to size & drilled holes & crimped wires', 'checked', false, 'page-text', 'Pages 28-30', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/drillcut.jpeg'),
    jsonb_build_object('index', 9, 'title', 'Fitted motors to chassis', 'checked', false, 'page-text', 'Page 31', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/motors.jpeg'),
    jsonb_build_object('index', 10, 'title', 'Fitted balancing wheels to chassis', 'checked', false, 'page-text', 'Page 32', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/balance.jpeg'),
    jsonb_build_object('index', 11, 'title', 'Fitted batteries to chassis', 'checked', false, 'page-text', 'Page 33', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/battery.jpeg'),
    jsonb_build_object('index', 12, 'title', 'Fitted rear safety lights & tow hook', 'checked', false, 'page-text', 'Page 34', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/rear.jpeg'),
    jsonb_build_object('index', 13, 'title', 'Soldered 1st PCB', 'checked', false, 'page-text', 'Pages 38-43', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/pcb.jpeg'),
    jsonb_build_object('index', 14, 'title', 'Soldered 2nd PCB', 'checked', false, 'page-text', 'Pages 38-43', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/pcb2.jpeg'),
    jsonb_build_object('index', 15, 'title', 'Made test equipment', 'checked', false, 'page-text', 'Page 44', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/testEquip.jpeg'),
    jsonb_build_object('index', 16, 'title', 'Checked 1st PCB board voltages (without PIC)', 'checked', false, 'page-text', 'Pages 46-47', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/voltages.jpeg'),
    jsonb_build_object('index', 17, 'title', 'Checked 2nd PCB board voltages (without PIC)', 'checked', false, 'page-text', 'Pages 46-47', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/voltages2.jpeg'),
    jsonb_build_object('index', 18, 'title', 'Tested 1st PCB LED (with PIC)', 'checked', false, 'page-text', 'Page 47', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/lamptest.jpeg'),
    jsonb_build_object('index', 19, 'title', 'Tested 2nd PCB LED (with PIC)', 'checked', false, 'page-text', 'Page 47', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/lamptest2.jpeg'),
    jsonb_build_object('index', 20, 'title', 'Tested 1st PCB with motor (with PIC & driver IC)', 'checked', false, 'page-text', 'Page 48', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/motortest.jpeg'),
    jsonb_build_object('index', 21, 'title', 'Tested 2nd PCB with motor (with PIC & driver IC)', 'checked', false, 'page-text', 'Page 48', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/motortest2.jpeg'),
    jsonb_build_object('index', 22, 'title', '1st PCB works!', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/pcbw1.jpeg'),
    jsonb_build_object('index', 23, 'title', '2nd PCB works!', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/pcbw2.jpeg'),
    jsonb_build_object('index', 24, 'title', 'Fitted PCB Boards to chassis', 'checked', false, 'page-text', 'Page 50', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/pcbs.jpeg'),
    jsonb_build_object('index', 25, 'title', 'Added a fuse and switch to wiring', 'checked', false, 'page-text', 'Page 52', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/fuse.jpeg'),
    jsonb_build_object('index', 26, 'title', 'Driven working chariot around!', 'checked', false, 'page-text', 'Page 51', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/drive.jpeg'),
    jsonb_build_object('index', 27, 'title', 'Arrived at Leonardo on the 27th of June for the competition', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/site.jpeg'),
    jsonb_build_object('index', 28, 'title', 'Fitted Radio Receiver to chassis', 'checked', false, 'page-text', 'Page 35', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/radio.jpeg'),
    jsonb_build_object('index', 29, 'title', 'Adjusted remote controller trim', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/trim.jpeg'),
    jsonb_build_object('index', 30, 'title', 'Performed the M.O.T.', 'checked', false, 'page-text', '', 'img-url', 'https://togmxgkpdfmfklcungfa.supabase.co/storage/v1/object/public/Roadmap-Images/mot.jpeg')
  );
$$;

create or replace function public.apply_progress_template(p_template jsonb, p_progress jsonb)
returns jsonb
language sql
stable
as $$
  with template as (
    select item, ordinality
    from jsonb_array_elements(p_template) with ordinality as t(item, ordinality)
  ),
  source as (
    select item
    from jsonb_array_elements(p_progress) as s(item)
  )
  select jsonb_agg(
    template.item || jsonb_build_object(
      'checked',
      coalesce((
        select (source.item->>'checked')::boolean
        from source
        where (source.item->>'index')::integer = (template.item->>'index')::integer
        limit 1
      ), false)
    )
    order by template.ordinality
  )
  from template;
$$;

drop function if exists public.get_school_names();
drop function if exists public.verify_school_password(text, text);
drop function if exists public.get_school_progress(text, text);

create or replace function public.get_school_names(p_site text default 'Luton')
returns text[]
language plpgsql
security definer
set search_path = public
as $$
declare
  result text[];
  table_name text := public.site_schools_table(p_site);
begin
  execute format(
    'select coalesce(array_agg(sp.school order by sp.school), ''{}''::text[])
     from public.%I sp',
    table_name
  )
  into result;

  return result;
end;
$$;

create or replace function public.verify_school_password(
  p_name text,
  p_password text,
  p_site text default 'Luton'
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object('success', public.school_password_matches(p_name, p_password, p_site));
$$;

create or replace function public.get_school_progress(
  p_name text,
  p_password text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  table_name text := public.site_schools_table(p_site);
begin
  execute format(
    'select coalesce(
      (
        select jsonb_build_object(
          ''school'',
          sp.school,
          ''progress'',
          public.apply_progress_template(
            (select admin.progress from public.%1$I admin where admin.school = ''Admin'' limit 1),
            sp.progress
          )
        )
        from public.%1$I sp
        where lower(sp.school) = lower(trim($1))
          and sp.password = $2
        limit 1
      ),
      jsonb_build_object(''error'', ''School not found or incorrect password'')
    )',
    table_name
  )
  into result
  using p_name, p_password;

  return result;
end;
$$;

create or replace function public.list_school_progress(
  p_name text default null,
  p_password text default null,
  p_admin_key text default null,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  table_name text := public.site_schools_table(p_site);
begin
  if not (
    public.admin_password_matches(coalesce(p_admin_key, ''), p_site)
    or public.school_password_matches(coalesce(p_name, ''), coalesce(p_password, ''), p_site)
  ) then
    raise exception 'Not authorised' using errcode = '28000';
  end if;

  execute format(
    'select coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            ''school'',
            sp.school,
            ''progress'',
            public.apply_progress_template(
              (select admin.progress from public.%1$I admin where admin.school = ''Admin'' limit 1),
              sp.progress
            )
          )
          order by sp.school
        )
        from public.%1$I sp
      ),
      ''[]''::jsonb
    )',
    table_name
  )
  into result;

  return result;
end;
$$;

drop function if exists public.list_school_progress(text, text, text);
drop function if exists public.create_school(text, text, text);

create or replace function public.create_school(
  p_admin_key text,
  p_name text,
  p_password text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_school record;
  table_name text := public.site_schools_table(p_site);
begin
  if not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  if nullif(trim(p_name), '') is null or nullif(p_password, '') is null then
    raise exception 'School name and password are required' using errcode = '22023';
  end if;

  execute format(
    'insert into public.%I (school, password, progress, comments)
     values (trim($1), $2, public.default_progress_steps(), ''[]''::jsonb)
     returning *',
    table_name
  )
  into created_school
  using p_name, p_password;

  return jsonb_build_object(
    'school', created_school.school,
    'progress', created_school.progress,
    'comments', created_school.comments
  );
exception
  when unique_violation then
    raise exception 'School already exists' using errcode = '23505';
end;
$$;

drop function if exists public.delete_school(text, text, text);

create or replace function public.delete_school(
  p_admin_key text,
  p_name text,
  p_password text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_school text;
  table_name text := public.site_schools_table(p_site);
begin
  if not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  execute format(
    'delete from public.%I sp
     where lower(sp.school) = lower(trim($1))
       and sp.password = $2
       and sp.school <> ''Admin''
     returning sp.school',
    table_name
  )
  into deleted_school
  using p_name, p_password;

  if deleted_school is null then
    raise exception 'School not found or incorrect password' using errcode = '02000';
  end if;

  return jsonb_build_object(
    'success', true,
    'message', format('School "%s" deleted successfully', deleted_school)
  );
end;
$$;

drop function if exists public.update_school_progress(text, text, jsonb);

create or replace function public.update_school_progress(
  p_name text,
  p_password text,
  p_progress jsonb,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_school record;
  table_name text := public.site_schools_table(p_site);
begin
  execute format(
    'update public.%I sp
     set progress = $3
     where lower(sp.school) = lower(trim($1))
       and sp.password = $2
     returning *',
    table_name
  )
  into updated_school
  using p_name, p_password, p_progress;

  if updated_school is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  return jsonb_build_object('school', updated_school.school, 'progress', updated_school.progress);
end;
$$;

create or replace function public.update_roadmap_image(
  p_admin_key text,
  p_step_index integer,
  p_img_url text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_progress jsonb;
  updated_progress jsonb;
  matched_count integer;
  table_name text := public.site_schools_table(p_site);
begin
  if not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  if p_step_index is null or p_step_index < 0 then
    raise exception 'Invalid roadmap step index' using errcode = '22023';
  end if;

  if nullif(trim(p_img_url), '') is null then
    raise exception 'Image URL is required' using errcode = '22023';
  end if;

  execute format(
    'select sp.progress
     from public.%I sp
     where sp.school = ''Admin''
     for update',
    table_name
  )
  into admin_progress;

  if admin_progress is null then
    raise exception 'Admin roadmap not found' using errcode = '02000';
  end if;

  select count(*)::integer
  into matched_count
  from jsonb_array_elements(admin_progress) as item
  where (item->>'index')::integer = p_step_index;

  if matched_count = 0 then
    raise exception 'Roadmap step not found' using errcode = '02000';
  end if;

  select jsonb_agg(
    case
      when (item->>'index')::integer = p_step_index then item || jsonb_build_object('img-url', trim(p_img_url))
      else item
    end
    order by ordinality
  )
  into updated_progress
  from jsonb_array_elements(admin_progress) with ordinality as steps(item, ordinality);

  execute format(
    'update public.%I
     set progress = $1
     where school = ''Admin''',
    table_name
  )
  using updated_progress;

  return jsonb_build_object(
    'success', true,
    'index', p_step_index,
    'img-url', trim(p_img_url)
  );
end;
$$;

drop function if exists public.update_roadmap_image(text, integer, text);

create or replace function public.reset_all_progress(
  p_admin_key text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  table_name text := public.site_schools_table(p_site);
begin
  if not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin password' using errcode = '28000';
  end if;

  execute format(
    'update public.%I
     set progress = (
       select jsonb_agg(jsonb_set(item, ''{checked}'', ''false''::jsonb) order by ordinality)
       from jsonb_array_elements(progress) with ordinality as steps(item, ordinality)
     )
     where school <> ''Admin''',
    table_name
  );

  return jsonb_build_object('success', true, 'message', 'All school progress has been reset');
end;
$$;

drop function if exists public.reset_all_progress(text);

create or replace function public.get_comments(
  p_school_name text,
  p_school_key text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  table_name text := public.site_schools_table(p_site);
begin
  execute format(
    'select coalesce(
      (
        select jsonb_build_object(''comments'', sp.comments)
        from public.%I sp
        where lower(sp.school) = lower(trim($1))
          and sp.password = $2
        limit 1
      ),
      jsonb_build_object(''error'', ''School not found or incorrect password'')
    )',
    table_name
  )
  into result
  using p_school_name, p_school_key;

  return result;
end;
$$;

create or replace function public.add_comment(
  p_school_name text,
  p_school_key text,
  p_text text,
  p_admin_key text default null,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_row record;
  current_comments jsonb;
  new_comment jsonb;
  new_index integer;
  sender text;
  table_name text := public.site_schools_table(p_site);
begin
  if nullif(trim(p_text), '') is null then
    raise exception 'Comment text is required' using errcode = '22023';
  end if;

  if p_admin_key is not null and not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin key' using errcode = '28000';
  end if;

  execute format(
    'select *
     from public.%I sp
     where lower(sp.school) = lower(trim($1))
       and sp.password = $2
     for update',
    table_name
  )
  into school_row
  using p_school_name, p_school_key;

  if school_row is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  current_comments := coalesce(school_row.comments, '[]'::jsonb);
  new_index := jsonb_array_length(current_comments);
  sender := case when p_admin_key is null then 'school' else 'leonardo' end;
  new_comment := jsonb_build_object('index', new_index, 'sender', sender, 'text', p_text, 'viewed', false);

  execute format(
    'update public.%I
     set comments = $1 || jsonb_build_array($2)
     where id = $3',
    table_name
  )
  using current_comments, new_comment, school_row.id;

  return jsonb_build_object('success', true, 'comment', new_comment);
end;
$$;

create or replace function public.delete_comment(
  p_school_name text,
  p_school_key text,
  p_comment_index integer,
  p_admin_key text,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_row record;
  updated_comments jsonb;
  table_name text := public.site_schools_table(p_site);
begin
  if not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin key' using errcode = '28000';
  end if;

  execute format(
    'select *
     from public.%I sp
     where lower(sp.school) = lower(trim($1))
       and sp.password = $2
     for update',
    table_name
  )
  into school_row
  using p_school_name, p_school_key;

  if school_row is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  if p_comment_index < 0 or p_comment_index >= jsonb_array_length(school_row.comments) then
    raise exception 'Invalid comment index' using errcode = '22023';
  end if;

  select coalesce(
    jsonb_agg((comment - 'index') || jsonb_build_object('index', new_index) order by new_index),
    '[]'::jsonb
  )
  into updated_comments
  from (
    select
      comment,
      row_number() over (order by ordinality) - 1 as new_index
    from jsonb_array_elements(school_row.comments) with ordinality as items(comment, ordinality)
    where (comment->>'index')::integer <> p_comment_index
  ) reindexed;

  execute format(
    'update public.%I
     set comments = $1
     where id = $2',
    table_name
  )
  using updated_comments, school_row.id;

  return jsonb_build_object('success', true, 'comments', updated_comments);
end;
$$;

create or replace function public.mark_comment_viewed(
  p_school_name text,
  p_school_key text,
  p_msg_index integer,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  school_row record;
  updated_comments jsonb;
  viewed_comment jsonb;
  table_name text := public.site_schools_table(p_site);
begin
  execute format(
    'select *
     from public.%I sp
     where lower(sp.school) = lower(trim($1))
       and sp.password = $2
     for update',
    table_name
  )
  into school_row
  using p_school_name, p_school_key;

  if school_row is null then
    raise exception 'School not found or incorrect password' using errcode = '28000';
  end if;

  if p_msg_index < 0 or p_msg_index >= jsonb_array_length(school_row.comments) then
    raise exception 'Invalid message index' using errcode = '22023';
  end if;

  select jsonb_agg(
    case
      when (comment->>'index')::integer = p_msg_index then jsonb_set(comment, '{viewed}', 'true'::jsonb)
      else comment
    end
    order by ordinality
  )
  into updated_comments
  from jsonb_array_elements(school_row.comments) with ordinality as items(comment, ordinality);

  select comment
  into viewed_comment
  from jsonb_array_elements(updated_comments) comment
  where (comment->>'index')::integer = p_msg_index
  limit 1;

  execute format(
    'update public.%I
     set comments = $1
     where id = $2',
    table_name
  )
  using updated_comments, school_row.id;

  return jsonb_build_object('success', true, 'comment', viewed_comment);
end;
$$;

create or replace function public.get_unviewed_comments(
  p_admin_key text,
  p_sent_by text default null,
  p_site text default 'Luton'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  table_name text := public.site_schools_table(p_site);
begin
  if not public.admin_password_matches(p_admin_key, p_site) then
    raise exception 'Incorrect admin key' using errcode = '28000';
  end if;

  execute format(
    'select coalesce(jsonb_object_agg(school, unviewed_count), ''{}''::jsonb)
     from (
       select sp.school, count(*)::integer as unviewed_count
       from public.%I sp
       cross join lateral jsonb_array_elements(sp.comments) comment
       where sp.school <> ''Admin''
         and (comment->>''viewed'')::boolean = false
         and (
           $1 is null
           or $1 not in (''leonardo'', ''school'')
           or comment->>''sender'' = $1
         )
       group by sp.school
     ) counts',
    table_name
  )
  into result
  using p_sent_by;

  return result;
end;
$$;

grant execute on function public.get_school_names(text) to anon, authenticated;
grant execute on function public.verify_school_password(text, text, text) to anon, authenticated;
grant execute on function public.get_school_progress(text, text, text) to anon, authenticated;
grant execute on function public.list_school_progress(text, text, text, text) to anon, authenticated;
grant execute on function public.create_school(text, text, text, text) to anon, authenticated;
grant execute on function public.delete_school(text, text, text, text) to anon, authenticated;
grant execute on function public.update_school_progress(text, text, jsonb, text) to anon, authenticated;
grant execute on function public.update_roadmap_image(text, integer, text, text) to anon, authenticated;
grant execute on function public.reset_all_progress(text, text) to anon, authenticated;
grant execute on function public.get_comments(text, text, text) to anon, authenticated;
grant execute on function public.add_comment(text, text, text, text, text) to anon, authenticated;
grant execute on function public.delete_comment(text, text, integer, text, text) to anon, authenticated;
grant execute on function public.mark_comment_viewed(text, text, integer, text) to anon, authenticated;
grant execute on function public.get_unviewed_comments(text, text, text) to anon, authenticated;

insert into public."Luton_schools" (school, password, progress, comments)
values
  ('Admin', 'lu13pg', public.default_progress_steps(), '[]'::jsonb),
  ('Cottesloe', 'cottesloe37355', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Queensbury', 'queensbury67890', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  --('Aylesbury High', 'aylesburyhigh54321', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Parmiters', 'parmiters98765', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  --('Stopsley', 'stopsley11223', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Silverstone UTC', 'silverstoneutc44556', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Roundwood', 'roundwood77889', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Watford Boys', 'watfordboys99001', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Watford Girls', 'watfordgirls22334', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Chalk Hills', 'chalkhills55667', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('St Clement Danes', 'stclementdanes88990', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  --('Lealands', 'lealands33445', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  --('Chiltern Academy', 'chilternacademy66778', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Shenley Brook End', 'shenleybrookend91402', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb)
on conflict (school) do nothing;

insert into public."Edinburgh_schools" (school, password, progress, comments)
values
  ('Admin', 'eh52xs', public.default_progress_steps(), '[]'::jsonb),
  ('Example School 1', 'exampleschool1', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Example School 2', 'exampleschool2', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Example School 3', 'exampleschool3', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb)
on conflict (school) do nothing;

insert into public."Basildon_schools" (school, password, progress, comments)
values
  ('Admin', 'ss143el', public.default_progress_steps(), '[]'::jsonb),
  ('Example School 1', 'exampleschool1', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Example School 2', 'exampleschool2', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb),
  ('Example School 3', 'exampleschool3', public.default_progress_steps(), '[{"index":0,"sender":"leonardo","text":"Hi there! How can we help?","viewed":false}]'::jsonb)
on conflict (school) do nothing;
